version: '3.7'

services:
  app:
    image: app
    container_name: app
    restart: always
    user: user
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.app.schedule: "@every 1m"
      ofelia.job-exec.app.command: "task"
#      ofelia.job-exec.app.slack-webhook: "slack-webhook-url"

  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    depends_on:
      - app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro